//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyApp.Client.ServiceClients.ServiceReferences {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NomenclatureInput", Namespace="http://schemas.datacontract.org/2004/07/PharmacyApp.Server.App.Models")]
    [System.SerializableAttribute()]
    public partial class NomenclatureInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PharmacyApp.Client.ServiceClients.ServiceReferences.NomenclatureInputType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidationRegexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Length {
            get {
                return this.LengthField;
            }
            set {
                if ((object.ReferenceEquals(this.LengthField, value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PharmacyApp.Client.ServiceClients.ServiceReferences.NomenclatureInputType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidationRegex {
            get {
                return this.ValidationRegexField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationRegexField, value) != true)) {
                    this.ValidationRegexField = value;
                    this.RaisePropertyChanged("ValidationRegex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NomenclatureInputType", Namespace="http://schemas.datacontract.org/2004/07/PharmacyApp.Server.Models")]
    public enum NomenclatureInputType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Date = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferences.INomenclatureInputsService")]
    public interface INomenclatureInputsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomenclatureInputsService/GetAllNomenclatureInputs", ReplyAction="http://tempuri.org/INomenclatureInputsService/GetAllNomenclatureInputsResponse")]
        PharmacyApp.Client.ServiceClients.ServiceReferences.NomenclatureInput[] GetAllNomenclatureInputs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INomenclatureInputsService/GetAllNomenclatureInputs", ReplyAction="http://tempuri.org/INomenclatureInputsService/GetAllNomenclatureInputsResponse")]
        System.Threading.Tasks.Task<PharmacyApp.Client.ServiceClients.ServiceReferences.NomenclatureInput[]> GetAllNomenclatureInputsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INomenclatureInputsServiceChannel : PharmacyApp.Client.ServiceClients.ServiceReferences.INomenclatureInputsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NomenclatureInputsServiceClient : System.ServiceModel.ClientBase<PharmacyApp.Client.ServiceClients.ServiceReferences.INomenclatureInputsService>, PharmacyApp.Client.ServiceClients.ServiceReferences.INomenclatureInputsService {
        
        public NomenclatureInputsServiceClient() {
        }
        
        public NomenclatureInputsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NomenclatureInputsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NomenclatureInputsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NomenclatureInputsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PharmacyApp.Client.ServiceClients.ServiceReferences.NomenclatureInput[] GetAllNomenclatureInputs() {
            return base.Channel.GetAllNomenclatureInputs();
        }
        
        public System.Threading.Tasks.Task<PharmacyApp.Client.ServiceClients.ServiceReferences.NomenclatureInput[]> GetAllNomenclatureInputsAsync() {
            return base.Channel.GetAllNomenclatureInputsAsync();
        }
    }
}
